[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Devin Cornell", email = "devinj.cornell@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "criterium",
    "fastapi>=0.141.1",
    "firecrawl-py>=4.40.0",
    "google-genai>=2.20.0",
    "ipykernel>=7.3.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
    "uvicorn>=0.52.4",
]

[project.scripts]
app = "app:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
criterium = { workspace = true }
